version: "3.7"

services:
  db:
    container_name: laravel_db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - .docker/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
  
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      APP_ENV: dev
      DATABASE_URL: mysql://laravel:laravel@db/laravel
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf
      - .docker/laravel.dev.ini:/etc/php7/conf.d/laravel.ini
      - .docker/laravel.dev.ini:/etc/php7/cli/conf.d/laravel.ini
      - .docker/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - .docker/php-fpm.conf:/etc/php7/php-fpm.d/php-fpm.conf
      - .docker/supervisord.conf:/etc/supervisord.conf
      - .:/laravel:cached
    depends_on: 
      - db